services:
  portfolio-prod:
    image: portfolio-prod
    container_name: portfolio-prod
    build:
      context: .
      dockerfile: ./docker/prod.Dockerfile
    command: npm run start
    # command: tail -f /dev/null
    restart: always
    env_file:
      - ".env"
    ports:
      - 80:3000
    volumes:
      - ./logs/:/app/logs
    networks:
      - portfolio-prod-network

networks:
  portfolio-prod-network:
    driver: bridge
    name: portfolio-prod-network
