services:
  portfolio:
    image: portfolio
    container_name: portfolio
    build:
      context: .
      dockerfile: docker/local.Dockerfile
    command: npm run dev
    restart: always
    env_file:
      - ".env"
    ports:
      - 3000:3000
    volumes:
      - ./src/:/app/src
      - ./public/:/app/public
    networks:
      - portfolio-network

networks:
  portfolio-network:
    driver: bridge
    name: portfolio-network
